import type { Metadata, Viewport } from "next";
import "./globals.css";
import "../styles/player/artplayer-liquid-glass.css";
import Navbar from "@/components/Navbar";
import ParticleBackground from "@/components/ParticleBackground";

export const metadata: Metadata = {
  title: "LongTV",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    apple: '/favicon.svg',
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="fixed inset-0" style={{ background: 'linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)', zIndex: -2 }} />
        <div className="fixed inset-0" style={{ zIndex: -1 }}>
          <ParticleBackground />
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
